Fixed "Linking globals named 'iu_handle_timeout': symbol multiply defined" for fat lto
warning: Linking globals named 'iu_handle_timeout': symbol multiply defined!

error: failed to load bitcode of module "recursive.c1bfe41b-cgu.1":

warning: `recursive` (bin "recursive") generated 1 warning
error: could not compile `recursive` due to previous error; 1 warning emitted
make: *** [Makefile:41: target/x86_64-unknown-linux-gnu/release/recursive] Error 101

Fixes: cf87f2302886 ("Use a new, retained symbol to reference __iu_handle_timeout")
Signed-off-by: Ruowen Qin <ruowenq2@illinois.edu>